// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PrStatus string

const (
	PrStatusOPEN   PrStatus = "OPEN"
	PrStatusMERGED PrStatus = "MERGED"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus `json:"pr_status"`
	Valid    bool     `json:"valid"` // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type PrReviewer struct {
	PrID   string `db:"pr_id" json:"pr_id"`
	UserID string `db:"user_id" json:"user_id"`
}

type PullRequest struct {
	PrID      string             `db:"pr_id" json:"pr_id"`
	Name      string             `db:"name" json:"name"`
	AuthorID  string             `db:"author_id" json:"author_id"`
	Status    PrStatus           `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MergedAt  pgtype.Timestamptz `db:"merged_at" json:"merged_at"`
}

type Team struct {
	TeamName string `db:"team_name" json:"team_name"`
}

type User struct {
	UserID   string `db:"user_id" json:"user_id"`
	Username string `db:"username" json:"username"`
	TeamName string `db:"team_name" json:"team_name"`
	IsActive bool   `db:"is_active" json:"is_active"`
}
