// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
)

const assignmentsPerPR = `-- name: AssignmentsPerPR :many
SELECT
  pr_id,
  COUNT(*)::int AS reviewer_count
FROM pr_reviewers
GROUP BY pr_id
ORDER BY pr_id
`

type AssignmentsPerPRRow struct {
	PrID          string `db:"pr_id" json:"pr_id"`
	ReviewerCount int32  `db:"reviewer_count" json:"reviewer_count"`
}

func (q *Queries) AssignmentsPerPR(ctx context.Context) ([]AssignmentsPerPRRow, error) {
	rows, err := q.db.Query(ctx, assignmentsPerPR)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentsPerPRRow{}
	for rows.Next() {
		var i AssignmentsPerPRRow
		if err := rows.Scan(&i.PrID, &i.ReviewerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assignmentsPerUser = `-- name: AssignmentsPerUser :many
SELECT
  user_id,
  COUNT(*)::int AS assigned_count
FROM pr_reviewers
GROUP BY user_id
ORDER BY assigned_count DESC, user_id
`

type AssignmentsPerUserRow struct {
	UserID        string `db:"user_id" json:"user_id"`
	AssignedCount int32  `db:"assigned_count" json:"assigned_count"`
}

func (q *Queries) AssignmentsPerUser(ctx context.Context) ([]AssignmentsPerUserRow, error) {
	rows, err := q.db.Query(ctx, assignmentsPerUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentsPerUserRow{}
	for rows.Next() {
		var i AssignmentsPerUserRow
		if err := rows.Scan(&i.UserID, &i.AssignedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
