// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, team_name, is_active
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const setIsActive = `-- name: SetIsActive :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, team_name, is_active
`

type SetIsActiveParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) SetIsActive(ctx context.Context, arg SetIsActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setIsActive, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (user_id, username, team_name, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET username  = EXCLUDED.username,
    team_name = EXCLUDED.team_name,
    is_active = EXCLUDED.is_active
RETURNING user_id, username, team_name, is_active
`

type UpsertUserParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Username string `db:"username" json:"username"`
	TeamName string `db:"team_name" json:"team_name"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}
